import { useEffect, useState } from 'react'
import type { MoveItem } from '../lib/items'

/**
 * The drafted request, on the item.
 *
 * Folded away by default: a twelve-line letter open on every row would bury the
 * state, the owner and the waiting time.
 *
 * There is no send button and no mail link. A link that opened a mail client
 * with the text already in it would be one click from sending, and `framing.md`
 * is not ambiguous - the model drafts, it never sends. Copying is the whole
 * affordance, and the request leaves as a message from the person.
 */
export function ItemDraft({
  item,
  isGeneral,
  busy,
  onGenerate,
  onSave,
}: {
  item: MoveItem
  /** True for an item added by hand, which has no verified facts behind it. */
  isGeneral: boolean
  busy: boolean
  onGenerate: () => void
  onSave: (draft: string) => void
}) {
  const [open, setOpen] = useState(false)
  const [text, setText] = useState(item.draft ?? '')
  const [copied, setCopied] = useState(false)

  // A draft regenerated by either person replaces what is in the box.
  useEffect(() => {
    setText(item.draft ?? '')
  }, [item.draft])

  if (!open) {
    return (
      <button
        className="button button--small button--quiet item__log-toggle"
        onClick={() => setOpen(true)}
      >
        {item.draft ? 'טיוטת הבקשה' : 'נסח בקשה'}
      </button>
    )
  }

  const edited = text.trim() !== (item.draft ?? '').trim()

  return (
    <div className="draft">
      <div className="actions">
        <button
          className="button button--small button--quiet"
          onClick={() => setOpen(false)}
        >
          סגור
        </button>

        <button className="button button--small" disabled={busy} onClick={onGenerate}>
          {busy ? 'מנסח…' : item.draft ? 'נסח מחדש' : 'נסח בקשה'}
        </button>

        {item.draft && (
          <button
            className="button button--small button--quiet"
            disabled={busy}
            onClick={() => {
              void navigator.clipboard.writeText(text).then(() => {
                setCopied(true)
                setTimeout(() => setCopied(false), 2000)
              })
            }}
          >
            {copied ? 'הועתק' : 'העתק'}
          </button>
        )}

        {edited && (
          <button
            className="button button--small"
            disabled={busy}
            onClick={() => onSave(text)}
          >
            שמור שינויים
          </button>
        )}
      </div>

      {isGeneral && item.draft && (
        <p className="draft__general">
          זו טיוטה כללית. הפריט נוסף ביד ואין עליו מידע מאומת, ולכן היא לא נוקבת
          בטופס, במחלקה או בנוהל — וגם לא במי שאליו היא מופנית.
        </p>
      )}

      {item.draft ? (
        <>
          <textarea
            className="draft__text"
            value={text}
            onChange={(event) => setText(event.target.value)}
            rows={14}
            disabled={busy}
          />
          <p className="draft__note">
            מה שבסוגריים מרובעים ממתין למילוי. הכלי לא שולח כלום — ההעתקה והשליחה
            שלך.
          </p>
        </>
      ) : (
        <p className="draft__note">
          עוד אין טיוטה. הניסוח נעשה מהפרטים המאומתים שברשימה בלבד.
        </p>
      )}
    </div>
  )
}
