import type { CatalogueItem } from './types'
import { ROUTES_BY_AUTHORITY_TYPE } from './routes'

/**
 * The nineteen items, transcribed from `docs/items.md`.
 *
 * `source` is that document's English, word for word. Everything else is Hebrew
 * written here, because the document is in English and the interface is not.
 * The Hebrew has no source behind it and is not checkable by machine.
 *
 * Nothing is added to this list that is not in that document.
 */
export const CATALOGUE: CatalogueItem[] = [
  {
    key: 'population_registry',
    position: 1,
    title: 'מרשם האוכלוסין — שינוי כתובת',
    detail: [
      'הרשות: רשות האוכלוסין וההגירה.',
      'ערוצים: מקוון דרך מערכת הזיהוי הממשלתית, עמדות שירות עצמי, לשכה, או בדואר. נספח תעודת הזהות המעודכן מגיע תוך חמישה ימי עבודה.',
    ],
    warnings: [
      'דואר שנשלח לכתובת הרשומה נחשב כאילו נמסר. על קנס שהגיע לכתובת הישנה אי אפשר לערער בדיעבד.',
    ],
    routes: null,
    order: 'זה הפריט הראשון. ביטוח לאומי לא יקבל כתובת חדשה לפני שמשרד הפנים רשם אותה.',
    unverified: null,
    source: [
      'Population registry — change of address',
      'Authority: Population and Immigration Authority.',
      'Routes: online through the government identification system, self-service stations, a bureau, or by post. The updated ID appendix arrives within five working days.',
      'Warning to show on the item: post sent to the registered address counts as delivered. A fine that arrived at the old address cannot be disputed afterwards.',
      'The population registry comes first. National Insurance will not accept a new address before the Interior Ministry has it.',
    ],
  },
  {
    key: 'national_insurance',
    position: 2,
    title: 'ביטוח לאומי',
    detail: ['אזור אישי מקוון, או טופס T900 בדואר או בסניף.'],
    warnings: [],
    routes: null,
    order: 'רק אחרי שפריט 1, מרשם האוכלוסין, הושלם.',
    unverified: null,
    source: [
      'National Insurance',
      'Only after item 1 is done. Personal area online, or form T900 by post or at a branch.',
    ],
  },
  {
    key: 'arnona_occupier',
    position: 3,
    title: 'ארנונה — החלפת מחזיק',
    detail: [
      'להביא: חוזה שכירות של שנים עשר חודשים או יותר, חתום בידי שני הצדדים; צילומים של שתי תעודות הזהות; שובר ארנונה שמופיע בו מספר הנכס.',
    ],
    warnings: [
      'שנים עשר החודשים נספרים מיום ההודעה. אי אפשר להגיש חוזה רטרואקטיבית.',
      'אם זה לא נעשה, החשבון נשאר על שם המחזיק הקודם וצובר חוב.',
      'חובה לדווח גם במעבר בתוך אותה רשות.',
    ],
    routes: ROUTES_BY_AUTHORITY_TYPE,
    order: null,
    unverified: null,
    source: [
      'Arnona — change of occupier',
      'Route depends on Sug_Muni.',
      'Needs: a rental contract of twelve months or more, signed by both sides; copies of both identity documents; an arnona voucher showing the property number.',
      'The twelve months are counted from the date of notice. A contract cannot be submitted retroactively.',
      "If this is not done, the account stays in the previous occupier's name and accrues debt.",
      'It must be reported even when moving within the same authority.',
    ],
  },
  {
    key: 'parking_permit',
    position: 4,
    title: 'תו חניה',
    detail: ['זמין לאחר הרישום ברשות.'],
    warnings: [],
    routes: ROUTES_BY_AUTHORITY_TYPE,
    order: null,
    unverified: null,
    source: [
      'Parking permit',
      'Route depends on Sug_Muni. Available once registered with the authority.',
    ],
  },
  {
    key: 'arnona_discount',
    position: 5,
    title: 'הנחה בארנונה',
    detail: ['רק אם יש זכאות.'],
    warnings: [],
    routes: ROUTES_BY_AUTHORITY_TYPE,
    order: null,
    unverified: null,
    source: ['Arnona discount', 'Route depends on Sug_Muni. Only if eligible.'],
  },
  {
    key: 'school_registration',
    position: 6,
    title: 'רישום לגן או לבית ספר',
    detail: ['רק אם רלוונטי.'],
    warnings: [],
    routes: ROUTES_BY_AUTHORITY_TYPE,
    order: null,
    unverified: null,
    source: [
      'Registration for kindergarten or school',
      'Route depends on Sug_Muni. Only if relevant.',
    ],
  },
  {
    key: 'residence_certificate',
    position: 7,
    title: 'אישור תושבות',
    detail: [
      'רק ביישובי פריפריה, לצורך הזיכוי במס הכנסה. ניתן לאחר שנים עשר חודשי מגורים, רטרואקטיבית לתחילתם.',
    ],
    warnings: [],
    routes: null,
    order: null,
    unverified: null,
    source: [
      'Certificate of residence',
      'Only in periphery settlements, for the income tax credit. Granted after twelve months of residence, backdated to the start.',
    ],
  },
  {
    key: 'electricity',
    position: 8,
    title: 'חשמל',
    detail: [
      'חברת החשמל לישראל. ערוצים: האתר, טופס בדואר אלקטרוני או בפקס למספר 1-800-200-103, או טלפון למספר 103.',
      'להביא: מספר החוזה או מספר החשבון מראש החשבונית, קריאת מונה עדכנית, ופרטים אישיים.',
    ],
    warnings: [],
    routes: null,
    order: null,
    unverified: null,
    source: [
      'Electricity',
      'Israel Electric Corporation. Routes: the website, a form by email or fax to 1-800-200-103, or by telephone to 103.',
      'Bring: the contract or account number from the top of the bill, a current meter reading, and personal details.',
    ],
  },
  {
    key: 'water',
    position: 9,
    title: 'מים',
    detail: ['תאגיד המים העירוני.'],
    warnings: [],
    routes: null,
    order: 'אחרי הארנונה.',
    unverified: null,
    source: [
      'Water',
      'The municipal water corporation. Comes after arnona.',
      'Arnona before water.',
    ],
  },
  {
    key: 'gas',
    position: 10,
    title: 'גז',
    detail: ['החברה שמספקת גז לדירה החדשה.'],
    warnings: [],
    routes: null,
    order: null,
    unverified: null,
    source: ['Gas', 'The company that supplies the new apartment.'],
  },
  {
    key: 'communications',
    position: 11,
    title: 'תקשורת',
    detail: ['טלפון, תשתית, ספק אינטרנט, טלוויזיה.'],
    warnings: [
      'להתחיל שבועיים עד שלושה שבועות מראש. תיאום טכנאי לוקח זמן.',
    ],
    routes: null,
    order: null,
    unverified: null,
    source: [
      'Communications',
      'Telephone, infrastructure, internet provider, television.',
      'Note to show on the item: start two to three weeks ahead. Arranging a technician takes time.',
    ],
  },
  {
    key: 'health_fund',
    position: 12,
    title: 'קופת חולים',
    detail: [],
    warnings: [],
    routes: null,
    order: null,
    unverified: null,
    source: ['Health fund'],
  },
  {
    key: 'banks',
    position: 13,
    title: 'בנקים וחברות כרטיסי אשראי',
    detail: [],
    warnings: [],
    routes: null,
    order: null,
    unverified: null,
    source: ['Banks and credit card companies'],
  },
  {
    key: 'home_insurance',
    position: 14,
    title: 'ביטוח דירה',
    detail: [],
    warnings: [],
    routes: null,
    order: null,
    unverified: null,
    source: ['Home insurance'],
  },
  {
    key: 'car_insurance',
    position: 15,
    title: 'ביטוח רכב',
    detail: [],
    warnings: [],
    routes: null,
    order: null,
    unverified: null,
    source: ['Car insurance'],
  },
  {
    key: 'pension_insurance',
    position: 16,
    title: 'ביטוח פנסיוני',
    detail: [],
    warnings: [],
    routes: null,
    order: null,
    unverified: null,
    source: ['Pension insurance'],
  },
  {
    key: 'idf',
    position: 17,
    title: 'צה"ל',
    detail: ['רק למשרתי מילואים פעילים.'],
    warnings: [],
    routes: null,
    order: null,
    unverified: null,
    source: ['IDF', 'Only for active reservists.'],
  },
  {
    key: 'subscriptions',
    position: 18,
    title: 'מנויים ושירותים',
    detail: [],
    warnings: [],
    routes: null,
    order: null,
    unverified: null,
    source: ['Subscriptions and services'],
  },
  {
    key: 'building_committee',
    position: 19,
    title: 'ועד בית',
    detail: [],
    warnings: [],
    routes: null,
    order: null,
    unverified: 'לא מתוך כל-זכות. נוסף בידי טומר וטרם אומת מול מקור.',
    source: [
      'Building committee',
      'Not from כל-זכות. Added by me and not yet verified against a source.',
    ],
  },
]

/** Keyed lookup, for rendering a `move_item` row from its `catalogue_key`. */
export const CATALOGUE_BY_KEY: ReadonlyMap<string, CatalogueItem> = new Map(
  CATALOGUE.map((item) => [item.key, item]),
)
